// web_dashboard/backend/services/caseService.js
const AMLCase = require('../models/AMLCase');
const { auditLog } = require('../utils/logger'); // For logging case creation

/**
 * Creates a new AML Case from alert data.
 * @param {object} alertData - The alert data object generated by amlEngineService.
 *                             Expected fields: ruleTriggered, summary, priority, 
 *                                            relatedTransactionId (or triggeringTransactions),
 *                                            triggeringWalletAddresses, associatedEntities.
 * @param {string|null} triggeredByUserId - The ID of the user who triggered the analysis, if applicable (e.g., manual scan). 
 *                                          Can be null for automated system events.
 * @returns {Promise<object|null>} The created AMLCase document or null if creation failed.
 */
const createCaseFromAlert = async (alertData, triggeredByUserId = 'System') => {
  if (!alertData || !alertData.ruleTriggered || !alertData.summary) {
    console.error('CaseService: Insufficient data to create AML case from alert.', alertData);
    auditLog('ERROR', 'AML_CASE_CREATION_FAILURE_DATA_INSUFFICIENT', triggeredByUserId, { alertData });
    return null;
  }

  try {
    // Generate a caseId - simple version for now.
    // The pre-validate hook in AMLCase model is commented out, so we need one here.
    // A more robust unique ID generator should be used in production.
    const caseId = `AML-${Date.now()}-${Math.random().toString(36).substring(2, 7).toUpperCase()}`;

    const newCaseData = {
      caseId: caseId,
      status: 'New', // Default status for new cases
      priority: alertData.priority || 'Medium',
      ruleTriggered: alertData.ruleTriggered,
      // Ensure triggeringTransactions is an array of ObjectIds if relatedTransactionId is primary
      triggeringTransactions: alertData.triggeringTransactions || (alertData.relatedTransactionId ? [alertData.relatedTransactionId] : []),
      // For triggeringWalletAddresses and associatedEntities, if they are arrays of strings (like addresses),
      // we'd ideally map them to corresponding _id references from WalletAddress/Entity models.
      // This is a complex step involving DB lookups and will be deferred for now.
      // For this iteration, if they are strings, they will not be directly queryable as refs yet.
      // The AMLCase schema expects ObjectIds for these.
      // For now, we'll pass them as is if they are just strings/basic info from alertData,
      // or ensure they are empty arrays if not provided.
      // This part needs careful handling based on what `amlEngineService` provides in `alertData`.
      // Let's assume `amlEngineService` provides an array of `ObjectId`s if possible, or we handle it here.
      // For now, let's assume `alertData.triggeringWalletAddresses` might be address strings from watchlist.
      // We will NOT try to convert them to ObjectIds in this step to keep it focused.
      // This means these fields in AMLCase might not be correctly populated with refs yet.
      triggeringWalletAddresses: alertData.triggeringWalletAddresses || [], // Placeholder for actual ObjectId refs
      associatedEntities: alertData.associatedEntities || [],       // Placeholder for actual ObjectId refs
      summary: alertData.summary,
      detailedDescription: alertData.detailedDescription || '', // Optional
      openedAt: new Date(),
      // assignedTo can be set later through case management actions
    };

    const amlCase = new AMLCase(newCaseData);
    const savedCase = await amlCase.save();

    console.log(`AML Case created successfully: ${savedCase.caseId}`);
    auditLog('INFO', 'AML_CASE_CREATED_SUCCESS', triggeredByUserId, { 
      caseId: savedCase.caseId, 
      rule: savedCase.ruleTriggered,
      priority: savedCase.priority,
      relatedTx: savedCase.triggeringTransactions.length > 0 ? savedCase.triggeringTransactions[0] : null 
    });

    return savedCase;

  } catch (error) {
    console.error('Error creating AML case in CaseService:', error.message);
    auditLog('ERROR', 'AML_CASE_CREATION_FAILURE', triggeredByUserId, { 
      alertRule: alertData.ruleTriggered, 
      error: error.message 
    });
    return null;
  }
};

// TODO: Add other case management functions later:
// - getCaseById(caseId)
// - updateCaseStatus(caseId, status, userId, notes)
// - assignCaseToUser(caseId, userIdToAssign, assignedByUserId)
// - addNoteToCase(caseId, note, authorId)
// - addAttachmentToCase(caseId, attachmentData, uploaderId)

module.exports = {
  createCaseFromAlert,
  // ... other functions when added
};
