// web_dashboard/backend/app.js
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors'); // For handling Cross-Origin Resource Sharing
const path = require('path'); // For serving static files from React build

// Import routes
const crimeRoutes = require('./routes/crime');
// const predictionRoutes = require('./routes/prediction'); // Placeholder for future prediction routes

// Initialize Express app
const app = express();

// --- Configuration ---
// Environment variables should be used for sensitive data like DB URI and port in a production environment
const PORT = process.env.PORT || 3001;
// Replace 'YOUR_MONGODB_CONNECTION_STRING_HERE' with your actual MongoDB connection string.
// For local development, it might be 'mongodb://localhost:27017/guardian_ai_db'
// For SAPS, this would be a secured, managed MongoDB instance.
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/guardian_ai_saps_db';

// --- Middleware ---
// Enable CORS - configure appropriately for production (e.g., whitelist specific origins)
app.use(cors()); 
// Parse JSON request bodies
app.use(express.json()); 
// Parse URL-encoded request bodies
app.use(express.urlencoded({ extended: true }));

// --- Database Connection ---
mongoose.connect(MONGODB_URI, {
  //useNewUrlParser: true, // Deprecated in newer Mongoose versions
  //useUnifiedTopology: true, // Deprecated
  //useCreateIndex: true, // Not supported
  //useFindAndModify: false // Not supported
}).then(() => {
  console.log('Successfully connected to MongoDB.');
}).catch(err => {
  console.error('MongoDB connection error:', err);
  // process.exit(1); // Optionally exit if DB connection fails
});

// --- API Routes ---
// Prefix all crime routes with /api/crime
app.use('/api/crime', crimeRoutes);
// app.use('/api/prediction', predictionRoutes); // Future: wire up prediction routes

// --- Serve React Frontend (Production) ---
// This section is for when you build your React app for production.
// The 'build' folder is typically generated by 'npm run build' in the React app.
if (process.env.NODE_ENV === 'production') {
  // Serve static files from the React app's build directory
  app.use(express.static(path.join(__dirname, '../frontend/build')));

  // For any other GET request, send back the React app's index.html file
  // This allows React Router to handle client-side routing.
  app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, '../frontend/build', 'index.html'));
  });
}

// --- Global Error Handler (Basic Example) ---
// This should be the last middleware added.
app.use((err, req, res, next) => {
  console.error('Global error handler:', err.stack);
  res.status(err.status || 500).json({
    message: err.message || 'An unexpected error occurred.',
    // Optionally include stack trace in development
    stack: process.env.NODE_ENV === 'development' ? err.stack : undefined,
  });
});

// --- Start Server ---
app.listen(PORT, () => {
  console.log(`Guardian AI Backend Server listening on port ${PORT}`);
  if (process.env.NODE_ENV !== 'production') {
    console.log('MongoDB URI:', MONGODB_URI); // Log URI in dev for easier debugging
    console.log('React frontend expected on http://localhost:3000 (if using default create-react-app port)');
    console.log('Proxy for frontend API requests is set to http://localhost:3001 in frontend package.json');
  }
});

// Export app for testing or other potential uses (though typically not needed if just running app.js)
// module.exports = app;
